# Fig pre block. Keep at the top of this file.
# [[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

zmodload zsh/zprof

# .files root directory
#
# expand %x since $0 is unreliable.
#
# TODO(js): Is there a 'cleaner' way to get this?
DF=${${(%):-%x}:A:h:h}

# oh-my-zsh locations
ZSH=$DF/zsh/oh-my-zsh
ZSH_CUSTOM=$DF/zsh/custom

# oh-my-zsh settings (config, theme, etc)
for f ($DF/zsh/*.zsh) source $f

# oh-my-zsh plugins
plugins=(
  aws
  bc
  # dash
  # direnv
  docker
  # dotnet
  encode64
  # extract
  # flamegraph
  fnm
  fzf
  # gem
  git
  git2
  go
  grc
  history
  history-substring-search
  homebrew
  iterm2
  # jira
  # k
  k8s
  # kafka
  localrc
  # nerdfont
  # nodenv
  # rbenv
  # ruby
  # slack-night-mode
  # touchbar
  # vagrant
  # web-search
  z
  zsh-autosuggestions
)

# User configuration
# Always work in a tmux session if tmux is installed
# https://github.com/chrishunt/dot-files/blob/master/.zshrc
# if which tmux 2>&1 >/dev/null; then
#   if [ $TERM != "screen-256color" ] && [  $TERM != "screen" ]; then
#     tmux attach -t hack || tmux new -s hack; exit
#   fi
# fi

# add homebrew functions and completions to fpath
if [ -d $HOMEBREW_ROOT/share/zsh/site-functions ]; then
  fpath=($HOMEBREW_ROOT/share/zsh/site-functions $fpath)
fi

# add local functions and completions to fpath
fpath=($DF/zsh/functions $fpath)
autoload -U $DF/zsh/functions/*(:t)

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# oh-my-zsh initializes completion before plugins are loaded.
# so reload here to pickup anything added to $fpath by plugins.
autoload -U compinit && compinit

# use .localrc for secrets, etc that you don't want in git
[ -L ~/.localrc ] && source ~/.localrc

# The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/josh/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/josh/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/josh/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/josh/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# Fig post block. Keep at the bottom of this file.
# [[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
