
# bullet train
ZSH_THEME="bullet-train"

BULLETTRAIN_AWS_FG=243 # light grey
BULLETTRAIN_AWS_SHOW=true
BULLETTRAIN_DIR_EXTENDED=2
BULLETTRAIN_EXEC_TIME_SHOW=true
BULLETTRAIN_GIT_ADDED=" 👶"
BULLETTRAIN_GIT_AHEAD=" 👆"
BULLETTRAIN_GIT_BEHIND=" 👇"
BULLETTRAIN_GIT_CLEAN=" ✔"
BULLETTRAIN_GIT_COLORIZE_DIRTY_BG_COLOR=242
BULLETTRAIN_GIT_COLORIZE_DIRTY_FG_COLOR=white #209
BULLETTRAIN_GIT_COLORIZE_DIRTY=true
BULLETTRAIN_GIT_DELETED=" 💣"
BULLETTRAIN_GIT_DIRTY=" 💩"
BULLETTRAIN_GIT_DIVERGED=" ⛓"
BULLETTRAIN_GIT_MODIFIED=" ✏️"
BULLETTRAIN_GIT_RENAMED=" 🚚"
BULLETTRAIN_GIT_UNTRACKED=" 👀"
BULLETTRAIN_GO_PREFIX=""
BULLETTRAIN_GO_SHOW=true
BULLETTRAIN_NVM_PREFIX=""
BULLETTRAIN_NVM_SHOW=false
BULLETTRAIN_PROMPT_CHAR="🐐" # 👉 💰
BULLETTRAIN_RUBY_PREFIX=""
BULLETTRAIN_RUBY_SHOW=false
BULLETTRAIN_STATUS_EXIT_SHOW=true